### ISSUE TITLE
部分UserAgent解析出错

### ISSUE THREAD

**Issue by Dodotry** [kaivean/python-ua-device#2]
部分UserAgent解析出错，另外，编译安装的时候需要相应改动导入的路径。
经过实际验证，在Internet Explorer处理环节会转float的时候会报错，需要将float(self.browser['version'])改成float(str(self.browser['version']))，最好加上try/except处理。
以下示例UA原始解析会报错：
Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; Trident/4.0; .NET CLR 2.0.50727)
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)

**Comment by kaivean** [comment]
嗯，我看下怎么处理

**Comment by kaivean** [comment]
看了下，这两个ua是可以正确解析的，你是用的哪个版本

**Comment by Dodotry** [comment]
> 看了下，这两个ua是可以正确解析的，你是用的哪个版本
我python 是3.8.2，用的版本是1.0.4版本，float(self.browser['version'])的时候有问题，str再次调用就没问题。
十分感谢，另外我稍微自己改了一下，匹配型号更准一些，例如iphone：
Server server-bag [iPhone OS,12.0.1,16A404,iPhone10,4]
com.apple.invitation-registration [iPhone OS,11.4,15F79,iPhone9,2]

**Comment by Dodotry** [comment]
> 看了下，这两个ua是可以正确解析的，你是用的哪个版本

我python 是3.8.2，用的版本是1.0.4版本，float(self.browser['version'])的时候有问题，str再次调用就没问题。
十分感谢，另外我稍微自己改了一下，匹配型号更准一些，例如iphone：
Server server-bag [iPhone OS,12.0.1,16A404,iPhone10,4]
com.apple.invitation-registration [iPhone OS,11.4,15F79,iPhone9,2]

**Comment by Dodotry** [comment]
Dalvik/2.1.0 (Linux; U; Android 8.1.0; M1813 Build/O11019)，这个解析不准确，解析成了Oppo，实际是魅族V8

**Comment by kaivean** [comment]
好，我加下

**Comment by Dodotry** [comment]
> 好，我加下

MobileSafari/* CFNetwork/* Darwin/*，这一类的解析会报错，还有其他的，例如：
MobileSafari/604.1 CFNetwork/978.0.7 Darwin/18.7.0
Safari 浏览器/13605.3.8 CFNetwork/902.1 Darwin/17.7.0 (x86_64)
com.apple.appstored/1.0 iOS/11.4 model/iPhone9,2 hwp/t8010 build/15F79 (6; dt:138)
Server server-bag [iPhone OS,12.0.1,16A404,iPhone10,4]
com.apple.invitation-registration [iPhone OS,11.4,15F79,iPhone9,2]

**Comment by kaivean** [comment]
如果是极少数的错误，可以尝试catch兼容性下，毕竟也会有异常格式

**Comment by Dodotry** [comment]
这种挺多的：
![image](https://user-images.githubusercontent.com/48266156/83242341-d3626f80-a1ce-11ea-8d38-6d9a7710aecd.png)

**Comment by kaivean** [comment]
对部分场景做了兼容和修复，发布1.0.5
