### ISSUE TITLE
对Oppo识别有点低

### ISSUE THREAD

**Issue by xiazhibin** [kaivean/python-ua-device#3]
```
Mozilla/5.0 (Linux; Android 9; V1932A Build/PKQ1.181030.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/68.0.3440.91 Mobile Safari/537.36
```
```
Mozilla/5.0 (Linux; Android 9; V1813BT Build/PKQ1.181030.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/68.0.3440.91 Mobile Safari/537.36
```
```
Mozilla/5.0 (Linux; Android 9; PCLM10 Build/PKQ1.190626.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/70.0.3538.110 Mobile Safari/537.36
```
这些也是Oppo系列

**Comment by kaivean** [comment]
我看下

发自我的iPhone

在 2020年6月7日，上午12:00，dingding <notifications@github.com> 写道：

﻿

Mozilla/5.0 (Linux; Android 9; V1932A Build/PKQ1.181030.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/68.0.3440.91 Mobile Safari/537.36


Mozilla/5.0 (Linux; Android 9; V1813BT Build/PKQ1.181030.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/68.0.3440.91 Mobile Safari/537.36


这两个也是Oppo系列

**Comment by xiazhibin** [comment]
其实Vivo跟Oppo有很多奇奇怪怪的型号，例如V18xxx,V19xxx这种是vivo家的。昨晚我跑了一下，一些比较新款的手机都没有识别出来，例如Mi 9 5G pro, 黑鲨，一加

**Comment by kaivean** [comment]
精确识别每个品牌是个花时间的活，同时一些小品牌绝大部分情况都没有用，所以很难一直投入人力在这上面

**Comment by kaivean** [comment]
FIX uaDevice-1.0.6

**Comment by xiazhibin** [comment]
那也是。可能我的数据里面比较多奇奇怪怪的型号。本地我自己也补充了一些进去
